#!/usr/bin/env node
/* =============================================================================
   build-content.js  —  M14 learning-object content pipeline
   =============================================================================

   DEVELOPMENT / BUILD-TIME TOOL. Not required by the browser at runtime and
   never fetched by the app. Node built-ins only, zero dependencies.

   Purpose
   -------
   The app's learning content (vocabulary, letters, marks, syllables, grammar
   points, texts) is authored as small reviewable files in content/*.json.
   This tool validates them and compiles them into a single `CONTENT` object
   spliced into index.html between AUTO-GENERATED markers, so the shipped app
   stays a single self-contained file with zero runtime dependencies and zero
   fetches.

   It does NOT author, translate, or invent content. It validates structure and
   cross-references only. (The linguistic linter — ḥarakāt coverage, natural
   usage, level-appropriateness — is a later milestone.)

   Usage
   -----
     node tools/build-content.js
         Validate content/*.json and report. No files written.

     node tools/build-content.js --check
         Validate, then compare the compiled block to what is in index.html.
         Exit 1 if index.html is stale. No files written. (CI / pre-commit.)

     node tools/build-content.js --write-app
         Validate, then refresh the CONTENT block inside index.html.

   Running it twice with no source change produces byte-identical output.
   Line-ending agnostic (see .gitattributes).
   ============================================================================= */

"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const CONTENT_DIR = path.join(ROOT, "content");
const INDEX_HTML = path.join(ROOT, "index.html");

const MARKER_START = "/* ===== AUTO-GENERATED by tools/build-content.js — do not edit by hand ===== */";
const MARKER_END = "/* ===== END AUTO-GENERATED (CONTENT) ===== */";

const FILES = {
    lexemes:   { file: "lexemes.json",   idPrefix: "lex:" },
    letters:   { file: "letters.json",   idPrefix: "let:" },
    marks:     { file: "marks.json",     idPrefix: "mrk:" },
    syllables: { file: "syllables.json", idPrefix: "syl:" },
    grammar:   { file: "grammar.json",   idPrefix: "gr:"  },
    texts:     { file: "texts.json",     idPrefix: "txt:" },
};

function lf(s) { return s == null ? s : s.replace(/\r\n/g, "\n"); }
function readJSON(p) { return JSON.parse(fs.readFileSync(p, "utf8")); }

/* -------------------------------------------------------------------------- */
/* Load + validate                                                           */
/* -------------------------------------------------------------------------- */
function load() {
    const errors = [];
    const data = {};

    for (const [key, cfg] of Object.entries(FILES)) {
        const p = path.join(CONTENT_DIR, cfg.file);
        let arr;
        try { arr = readJSON(p); }
        catch (e) { errors.push(`${cfg.file}: cannot parse — ${e.message}`); continue; }
        if (!Array.isArray(arr)) { errors.push(`${cfg.file}: expected a JSON array`); continue; }
        data[key] = arr;
    }

    let legacyMap;
    try { legacyMap = readJSON(path.join(CONTENT_DIR, "_legacy-id-map.json")); }
    catch (e) { errors.push(`_legacy-id-map.json: cannot parse — ${e.message}`); }

    if (errors.length) return { errors };

    /* ids: present, prefixed, globally unique */
    const allIds = new Set();
    for (const [key, cfg] of Object.entries(FILES)) {
        for (const [i, o] of data[key].entries()) {
            if (typeof o.id !== "string" || !o.id) { errors.push(`${cfg.file}[${i}]: missing string id`); continue; }
            if (!o.id.startsWith(cfg.idPrefix)) errors.push(`${cfg.file}: id "${o.id}" must start with "${cfg.idPrefix}"`);
            if (allIds.has(o.id)) errors.push(`duplicate id "${o.id}"`);
            allIds.add(o.id);
        }
    }

    /* lexemes: Arabic + transliteration present */
    for (const l of data.lexemes) {
        if (!l.ar) errors.push(`lexeme ${l.id}: missing "ar"`);
        if (!l.translit) errors.push(`lexeme ${l.id}: missing "translit"`);
    }

    /* invariants carried from earlier milestones */
    const shortVowels = data.marks.filter(m => m.markClass === "short-vowel").length;
    if (shortVowels !== 3) errors.push(`marks: expected exactly 3 short-vowel marks (HARAKAT), found ${shortVowels}`);
    if (data.letters.length !== 28) errors.push(`letters: expected 28, found ${data.letters.length}`);
    for (const m of data.marks.filter(m => m.markClass === "long-vowel")) {
        try { new RegExp(m.pattern); }
        catch (e) { errors.push(`mark ${m.id}: pattern "${m.pattern}" is not a valid RegExp — ${e.message}`); }
    }

    /* cross-references resolve */
    for (const s of data.syllables) {
        if (s.exampleWord && !allIds.has(s.exampleWord))
            errors.push(`syllable ${s.id}: exampleWord "${s.exampleWord}" does not resolve`);
    }
    for (const g of data.grammar) {
        for (const ref of g.examples || []) {
            if (!allIds.has(ref)) errors.push(`grammar ${g.id}: example "${ref}" does not resolve`);
        }
    }
    for (const t of data.texts) {
        if (!["m8", "m11"].includes(t.source)) errors.push(`text ${t.id}: source "${t.source}" must be m8 or m11`);
    }

    /* prereq graph: every edge resolves, no cycles (M14 has no prereqs — kept for later) */
    const graph = new Map();
    for (const key of Object.keys(FILES)) for (const o of data[key]) {
        graph.set(o.id, Array.isArray(o.prereqs) ? o.prereqs : []);
        for (const p of graph.get(o.id)) if (!allIds.has(p)) errors.push(`${o.id}: prereq "${p}" does not resolve`);
    }
    const cyc = findCycle(graph);
    if (cyc) errors.push(`prereq cycle: ${cyc.join(" → ")}`);

    /* legacy id map: keys 1..46, values are real lexeme ids, 1:1 */
    if (legacyMap) {
        const keys = Object.keys(legacyMap);
        for (let n = 1; n <= 46; n++) if (!(String(n) in legacyMap)) errors.push(`_legacy-id-map: missing key "${n}"`);
        if (keys.length !== 46) errors.push(`_legacy-id-map: expected 46 keys, found ${keys.length}`);
        const vals = Object.values(legacyMap);
        for (const v of vals) if (!allIds.has(v)) errors.push(`_legacy-id-map: "${v}" is not a real object id`);
        if (new Set(vals).size !== vals.length) errors.push(`_legacy-id-map: values are not 1:1 (a lexeme is claimed by two flashcards)`);
        for (const v of vals) {
            const lx = data.lexemes.find(l => l.id === v);
            if (lx && !(lx.tags || []).includes("legacy-flashcard"))
                errors.push(`_legacy-id-map: ${v} is mapped from a flashcard but is not tagged "legacy-flashcard"`);
        }
    }

    return { errors, data, legacyMap };
}

function findCycle(graph) {
    const WHITE = 0, GREY = 1, BLACK = 2;
    const color = new Map([...graph.keys()].map(k => [k, WHITE]));
    const stack = [];
    let cycle = null;
    function dfs(u) {
        color.set(u, GREY); stack.push(u);
        for (const v of graph.get(u) || []) {
            if (!graph.has(v)) continue;
            if (color.get(v) === GREY) { cycle = stack.slice(stack.indexOf(v)).concat(v); return true; }
            if (color.get(v) === WHITE && dfs(v)) return true;
        }
        color.set(u, BLACK); stack.pop(); return false;
    }
    for (const k of graph.keys()) if (color.get(k) === WHITE && dfs(k)) break;
    return cycle;
}

/* -------------------------------------------------------------------------- */
/* Compile                                                                   */
/* -------------------------------------------------------------------------- */
function compile(data, legacyMap) {
    // Source-file order is preserved verbatim — it is semantically meaningful
    // (letters run alif→yāʾ, harakāt fatḥah→ḍammah, reading passages in lesson
    // order, …). Deterministic because the JSON files are the source of truth.
    const section = (key) => {
        const rows = data[key].map(o => "  " + JSON.stringify(o) + ",");
        return `"${key}": [\n${rows.join("\n")}\n]`;
    };
    const mapRows = Object.keys(legacyMap)
        .sort((a, b) => Number(a) - Number(b))
        .map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(legacyMap[k])},`);

    return [
        MARKER_START,
        "/* Learning-object content, compiled from content/*.json by",
        "   tools/build-content.js. Do not hand-edit. Regenerate:",
        "     node tools/build-content.js --write-app */",
        "const CONTENT = {",
        section("lexemes") + ",",
        section("letters") + ",",
        section("marks") + ",",
        section("syllables") + ",",
        section("grammar") + ",",
        section("texts") + ",",
        `"legacyFlashcardId": {\n${mapRows.join("\n")}\n}`,
        "};",
        MARKER_END,
    ].join("\n");
}

function extractBlock(html) {
    const i = html.indexOf(MARKER_START);
    const j = html.indexOf(MARKER_END);
    if (i === -1 || j === -1) return null;
    return html.slice(i, j + MARKER_END.length);
}

/* -------------------------------------------------------------------------- */
/* Main                                                                      */
/* -------------------------------------------------------------------------- */
function main() {
    const args = new Set(process.argv.slice(2));
    const { errors, data, legacyMap } = load();

    if (errors.length) {
        console.error("content validation FAILED:");
        errors.forEach(e => console.error("  - " + e));
        process.exit(1);
    }

    const counts = Object.fromEntries(Object.keys(FILES).map(k => [k, data[k].length]));
    const block = compile(data, legacyMap);
    const html = fs.readFileSync(INDEX_HTML, "utf8");
    const current = extractBlock(html);

    if (args.has("--check")) {
        if (current === null) { console.error("--check: CONTENT markers not found in index.html"); process.exit(1); }
        if (lf(current) !== lf(block)) {
            console.error("STALE — index.html CONTENT block is out of date. Run: node tools/build-content.js --write-app");
            process.exit(1);
        }
        console.log(`content OK and index.html in sync — ${sum(counts)} objects (${describe(counts)}).`);
        return;
    }

    if (args.has("--write-app")) {
        if (current === null) {
            console.error("\n--write-app: CONTENT markers not found in index.html. Add this once, in the DATA section:\n");
            console.error(MARKER_START + "\nconst CONTENT = {};\n" + MARKER_END + "\n");
            process.exit(2);
        }
        const eol = html.includes("\r\n") ? "\r\n" : "\n";
        const updated = html.replace(current, block.replace(/\n/g, eol));
        if (lf(updated) === lf(html)) console.log("index.html CONTENT block already current.");
        else { fs.writeFileSync(INDEX_HTML, updated); console.log("updated index.html CONTENT block."); }
    }

    console.log("");
    console.log("content validated — " + sum(counts) + " learning objects");
    for (const [k, n] of Object.entries(counts)) console.log("  " + k.padEnd(12) + n);
    console.log("  legacy id map  " + Object.keys(legacyMap).length);
    if (!args.has("--write-app")) console.log("\n(run with --write-app to splice into index.html, or --check to verify)");
}

function sum(c) { return Object.values(c).reduce((a, b) => a + b, 0); }
function describe(c) { return Object.entries(c).map(([k, n]) => `${n} ${k}`).join(", "); }

main();
