#!/usr/bin/env node
/* =============================================================================
   build-content.js  —  M14 learning-object content pipeline
   =============================================================================

   DEVELOPMENT / BUILD-TIME TOOL. Not required by the browser at runtime and
   never fetched by the app. Node built-ins only, zero dependencies.

   Purpose
   -------
   The app's learning content (vocabulary, letters, marks, syllables, grammar
   points, texts) is authored as small reviewable files in content/*.json.
   This tool validates them and compiles them into a single `CONTENT` object
   spliced into index.html between AUTO-GENERATED markers, so the shipped app
   stays a single self-contained file with zero runtime dependencies and zero
   fetches.

   It does NOT author, translate, or invent content. It validates structure and
   cross-references only. (The linguistic linter — ḥarakāt coverage, natural
   usage, level-appropriateness — is a later milestone.)

   Usage
   -----
     node tools/build-content.js
         Validate content/*.json and report. No files written.

     node tools/build-content.js --check
         Validate, then compare the compiled block to what is in index.html.
         Exit 1 if index.html is stale. No files written. (CI / pre-commit.)

     node tools/build-content.js --write-app
         Validate, then refresh the CONTENT block inside index.html.

     node tools/build-content.js --lint
         Validate (as above — always on, always blocking), then print the
         full advisory report: M14.5 ḥarakāt-coverage + orphaned-object
         warnings, M20.5's texts.json reduced/unvowelled drift check, and
         M20's linguistic-lint WARNINGS (long-vowel / length / harakat /
         level-fit). Advisory only — --lint never exits non-zero on its own.
         No files written.

         M20's linguistic-lint HARD errors (colloquial register, misplaced
         Arabic-Indic digits, a translit/script emphatic mismatch) are not
         advisory: they block EVERY run, --lint or not.

   Running it twice with no source change produces byte-identical output.
   Line-ending agnostic (see .gitattributes).
   ============================================================================= */

"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const CONTENT_DIR = path.join(ROOT, "content");
const INDEX_HTML = path.join(ROOT, "index.html");

const MARKER_START = "/* ===== AUTO-GENERATED by tools/build-content.js — do not edit by hand ===== */";
const MARKER_END = "/* ===== END AUTO-GENERATED (CONTENT) ===== */";

const FILES = {
    lexemes:   { file: "lexemes.json",   idPrefix: "lex:" },
    letters:   { file: "letters.json",   idPrefix: "let:" },
    marks:     { file: "marks.json",     idPrefix: "mrk:" },
    syllables: { file: "syllables.json", idPrefix: "syl:" },
    grammar:   { file: "grammar.json",   idPrefix: "gr:"  },
    texts:     { file: "texts.json",     idPrefix: "txt:" },
};

function lf(s) { return s == null ? s : s.replace(/\r\n/g, "\n"); }
function readJSON(p) { return JSON.parse(fs.readFileSync(p, "utf8")); }

/* -------------------------------------------------------------------------- */
/* Load + validate                                                           */
/* -------------------------------------------------------------------------- */
function load() {
    const errors = [];
    const data = {};

    for (const [key, cfg] of Object.entries(FILES)) {
        const p = path.join(CONTENT_DIR, cfg.file);
        let arr;
        try { arr = readJSON(p); }
        catch (e) { errors.push(`${cfg.file}: cannot parse — ${e.message}`); continue; }
        if (!Array.isArray(arr)) { errors.push(`${cfg.file}: expected a JSON array`); continue; }
        data[key] = arr;
    }

    let legacyMap;
    try { legacyMap = readJSON(path.join(CONTENT_DIR, "_legacy-id-map.json")); }
    catch (e) { errors.push(`_legacy-id-map.json: cannot parse — ${e.message}`); }

    // M15 taxonomy — skills, levels (bare ids), and the descriptor grid.
    for (const [key, file] of [["skills", "skills.json"], ["levels", "levels.json"], ["descriptors", "descriptors.json"]]) {
        try {
            const arr = readJSON(path.join(CONTENT_DIR, file));
            if (!Array.isArray(arr)) errors.push(`${file}: expected a JSON array`);
            else data[key] = arr;
        } catch (e) { errors.push(`${file}: cannot parse — ${e.message}`); }
    }

    // M16 curriculum spine — an object { levels, units, lessons }, not an array.
    try {
        const cur = readJSON(path.join(CONTENT_DIR, "curriculum.json"));
        if (!cur || typeof cur !== "object" || Array.isArray(cur)) errors.push("curriculum.json: expected a JSON object");
        else if (!Array.isArray(cur.levels) || !Array.isArray(cur.units) || !Array.isArray(cur.lessons))
            errors.push("curriculum.json: must have array `levels`, `units`, `lessons`");
        else data.curriculum = cur;
    } catch (e) { errors.push(`curriculum.json: cannot parse — ${e.message}`); }

    // Catalog lesson ids live in index.html (`const lessons = { ... }`); read them
    // so `source: "steps:<id>"` can be validated. Missing/unreadable → skip that check.
    let catalogLessonIds = null;
    try {
        const appHtml = fs.readFileSync(INDEX_HTML, "utf8");
        const m = appHtml.match(/const lessons = \{([\s\S]*?)\n\};/);
        if (m) {
            catalogLessonIds = new Set();
            for (const mm of m[1].matchAll(/^ {4}"([a-z0-9-]+)":\s*\{/gm)) catalogLessonIds.add(mm[1]);
        }
    } catch (e) { /* index.html unreadable at load time — source check skipped */ }
    data._catalogLessonIds = catalogLessonIds;

    // M20 — the linguistic linter's inputs: the controlled word lists and the
    // deliberate-exception allow-list. Both optional.
    data._wordlists = {};
    try {
        const w = readJSON(path.join(CONTENT_DIR, "wordlists", "a1.json"));
        data._wordlists.a1 = Array.isArray(w) ? w : w.a1;
    } catch (e) { /* not authored yet */ }
    try { data._lintAllow = readJSON(path.join(CONTENT_DIR, "_lint-allow.json")); } catch (e) { data._lintAllow = {}; }

    // M20 — lessons authored as data. content/lessons/*.json, each a
    // { id, unitId?, title, level, skills, objectives, steps } object.
    data.lessons = [];
    try {
        const dir = path.join(CONTENT_DIR, "lessons");
        for (const f of fs.readdirSync(dir).filter(n => n.endsWith(".json")).sort()) {
            try { data.lessons.push(readJSON(path.join(dir, f))); }
            catch (e) { errors.push(`lessons/${f}: cannot parse — ${e.message}`); }
        }
    } catch (e) { /* no lessons dir yet */ }

    if (errors.length) return { errors };

    /* ids: present, prefixed, globally unique */
    const allIds = new Set();
    for (const [key, cfg] of Object.entries(FILES)) {
        for (const [i, o] of data[key].entries()) {
            if (typeof o.id !== "string" || !o.id) { errors.push(`${cfg.file}[${i}]: missing string id`); continue; }
            if (!o.id.startsWith(cfg.idPrefix)) errors.push(`${cfg.file}: id "${o.id}" must start with "${cfg.idPrefix}"`);
            if (allIds.has(o.id)) errors.push(`duplicate id "${o.id}"`);
            allIds.add(o.id);
        }
    }
    data._objById = new Map();
    for (const key of Object.keys(FILES)) for (const o of data[key]) data._objById.set(o.id, o);

    /* lexemes: Arabic + transliteration present */
    for (const l of data.lexemes) {
        if (!l.ar) errors.push(`lexeme ${l.id}: missing "ar"`);
        if (!l.translit) errors.push(`lexeme ${l.id}: missing "translit"`);
    }

    /* invariants carried from earlier milestones */
    const shortVowels = data.marks.filter(m => m.markClass === "short-vowel").length;
    if (shortVowels !== 3) errors.push(`marks: expected exactly 3 short-vowel marks (HARAKAT), found ${shortVowels}`);
    if (data.letters.length !== 28) errors.push(`letters: expected 28, found ${data.letters.length}`);
    for (const m of data.marks.filter(m => m.markClass === "long-vowel")) {
        try { new RegExp(m.pattern); }
        catch (e) { errors.push(`mark ${m.id}: pattern "${m.pattern}" is not a valid RegExp — ${e.message}`); }
    }

    /* cross-references resolve */
    for (const s of data.syllables) {
        if (s.exampleWord && !allIds.has(s.exampleWord))
            errors.push(`syllable ${s.id}: exampleWord "${s.exampleWord}" does not resolve`);
    }
    for (const g of data.grammar) {
        for (const ref of g.examples || []) {
            if (!allIds.has(ref)) errors.push(`grammar ${g.id}: example "${ref}" does not resolve`);
        }
    }
    for (const t of data.texts) {
        if (!["m8", "m11"].includes(t.source)) errors.push(`text ${t.id}: source "${t.source}" must be m8 or m11`);
    }

    /* prereq graph: every edge resolves, no cycles (M14 has no prereqs — kept for later) */
    const graph = new Map();
    for (const key of Object.keys(FILES)) for (const o of data[key]) {
        graph.set(o.id, Array.isArray(o.prereqs) ? o.prereqs : []);
        for (const p of graph.get(o.id)) if (!allIds.has(p)) errors.push(`${o.id}: prereq "${p}" does not resolve`);
    }
    const cyc = findCycle(graph);
    if (cyc) errors.push(`prereq cycle: ${cyc.join(" → ")}`);

    /* -------- M15: skills, levels, descriptors, object tags -------- */
    const skillIds = new Set((data.skills || []).map(s => s.id));
    const levelIds = (data.levels || []).map(l => l.id);
    const levelIdx = Object.fromEntries(levelIds.map((id, i) => [id, i]));

    if (skillIds.size !== (data.skills || []).length) errors.push("skills.json: duplicate skill id");
    if (new Set(levelIds).size !== levelIds.length) errors.push("levels.json: duplicate level id");
    for (const s of data.skills || []) if (!["reliable", "partial", "self-report"].includes(s.assess))
        errors.push(`skill ${s.id}: assess "${s.assess}" must be reliable | partial | self-report`);

    /* descriptors: exactly one per (skill × level), each with canDo + source */
    if (data.descriptors && data.skills && data.levels) {
        const want = skillIds.size * levelIds.length;
        if (data.descriptors.length !== want)
            errors.push(`descriptors.json: expected ${want} cells (${skillIds.size} skills × ${levelIds.length} levels), found ${data.descriptors.length}`);
        const seen = new Set();
        for (const d of data.descriptors) {
            const key = `${d.skill}/${d.level}`;
            if (!skillIds.has(d.skill)) errors.push(`descriptor ${key}: unknown skill`);
            if (!(d.level in levelIdx)) errors.push(`descriptor ${key}: unknown level`);
            if (seen.has(key)) errors.push(`descriptor ${key}: duplicate cell`);
            seen.add(key);
            if (!d.canDo || !d.canDo.trim()) errors.push(`descriptor ${key}: empty canDo`);
            if (!d.source || !d.source.trim()) errors.push(`descriptor ${key}: empty source`);
        }
        for (const s of skillIds) for (const l of levelIds)
            if (!seen.has(`${s}/${l}`)) errors.push(`descriptors.json: missing cell ${s}/${l}`);
    }

    /* every learning object: a valid level + ≥1 valid skill */
    for (const key of Object.keys(FILES)) for (const o of data[key]) {
        if (!o.level || !(o.level in levelIdx)) errors.push(`${o.id}: level "${o.level}" is not in levels.json`);
        if (!Array.isArray(o.skills) || o.skills.length === 0) errors.push(`${o.id}: missing skills[]`);
        else for (const sk of o.skills) if (!skillIds.has(sk)) errors.push(`${o.id}: unknown skill "${sk}"`);
    }

    /* M17: every measurable placement strand must have objects at ≥ 2 distinct
       levels, or its adaptive diagnostic can't form bands. */
    const PLACEMENT_MEASURED = ["reading", "vocabulary", "grammar", "listening", "comprehension"];
    for (const strand of PLACEMENT_MEASURED) {
        const levelsWithObjects = new Set();
        for (const key of Object.keys(FILES)) for (const o of data[key])
            if ((o.skills || []).includes(strand) && (o.level in levelIdx)) levelsWithObjects.add(o.level);
        if (levelsWithObjects.size < 2)
            errors.push(`placement: strand "${strand}" has objects at only ${levelsWithObjects.size} level(s) — the diagnostic needs ≥ 2`);
    }

    /* M18: each exercise kind needs raw material to generate at least one item. */
    const topicSizes = {};
    for (const l of data.lexemes) topicSizes[l.topic] = (topicSizes[l.topic] || 0) + 1;
    if (!Object.values(topicSizes).some(n => n >= 4))
        errors.push(`exercise "match": no lexeme topic has ≥ 4 words`);
    const textsWithWords = data.texts.filter(t => Array.isArray(t.words) && t.words.length >= 3);
    if (!textsWithWords.length)
        errors.push(`exercise "cloze"/"order": no text has words[] of length ≥ 3`);
    const AR_MARK = /[ؐ-ًؚ-ٰٟۖ-ۭ]/;
    const graphemeCount = s => (String(s).match(new RegExp("[^\\s" + AR_MARK.source.slice(1, -1) + "]", "g")) || []).length;
    if (!data.lexemes.some(l => { const g = graphemeCount(l.ar); return g >= 3 && g <= 6; }))
        errors.push(`exercise "build": no lexeme spells to 3–6 base letters`);

    /* prereq graph must be level-monotonic: a prereq is never a higher level than its dependent */
    const objLevel = {};
    for (const key of Object.keys(FILES)) for (const o of data[key]) objLevel[o.id] = o.level;
    for (const [id, prereqs] of graph) for (const p of prereqs) {
        if (objLevel[p] && objLevel[id] && levelIdx[objLevel[p]] > levelIdx[objLevel[id]])
            errors.push(`${id} (${objLevel[id]}) has a higher-level prereq ${p} (${objLevel[p]})`);
    }

    /* -------- M16: curriculum spine — levels / units / lessons -------- */
    if (data.curriculum) {
        const cur = data.curriculum;
        const objLevelOf = id => objLevel[id];   // from the M15 block above
        const STATUS = ["available", "preview", "planned"];

        /* levels: id ∈ levels.json, unique, no extras/omissions */
        const curLevelIds = cur.levels.map(l => l.id);
        for (const l of cur.levels) {
            if (!(l.id in levelIdx)) errors.push(`curriculum level "${l.id}" is not in levels.json`);
            if (!["available", "planned"].includes(l.status)) errors.push(`curriculum level ${l.id}: status "${l.status}" must be available | planned`);
        }
        if (new Set(curLevelIds).size !== curLevelIds.length) errors.push("curriculum.levels: duplicate level id");
        for (const id of levelIds) if (!curLevelIds.includes(id)) errors.push(`curriculum.levels: missing level "${id}"`);

        /* units: unique id, valid level, valid status, resolvable + acyclic + level-monotonic prereqs */
        const unitIds = new Set();
        for (const u of cur.units) {
            if (unitIds.has(u.id)) errors.push(`curriculum unit "${u.id}": duplicate id`);
            unitIds.add(u.id);
            if (!(u.level in levelIdx)) errors.push(`curriculum unit ${u.id}: level "${u.level}" is not in levels.json`);
            if (!["available", "planned"].includes(u.status)) errors.push(`curriculum unit ${u.id}: status "${u.status}" must be available | planned`);
            if (!u.title || !u.title.trim()) errors.push(`curriculum unit ${u.id}: empty title`);
            if (!Array.isArray(u.skills) || u.skills.some(s => !skillIds.has(s))) errors.push(`curriculum unit ${u.id}: skills must all be valid skill ids`);
        }
        const unitGraph = new Map();
        for (const u of cur.units) {
            const pr = Array.isArray(u.prereqs) ? u.prereqs : [];
            unitGraph.set(u.id, pr);
            for (const p of pr) {
                if (!unitIds.has(p)) errors.push(`curriculum unit ${u.id}: prereq "${p}" does not resolve`);
                else {
                    const pl = cur.units.find(x => x.id === p).level;
                    if (levelIdx[pl] > levelIdx[u.level]) errors.push(`curriculum unit ${u.id} (${u.level}): prereq ${p} is a higher level (${pl})`);
                }
            }
        }
        const unitCyc = findCycle(unitGraph);
        if (unitCyc) errors.push(`curriculum unit prereq cycle: ${unitCyc.join(" → ")}`);

        /* lessons: unique id, real unit, valid level+status, objectives resolve,
           lesson.level ≥ every objective's level, source well-formed */
        const lessonIds = new Set();
        const VIEW_TARGETS = new Set(["alphabet", "vocabulary"]);
        for (const ls of cur.lessons) {
            if (lessonIds.has(ls.id)) errors.push(`curriculum lesson "${ls.id}": duplicate id`);
            lessonIds.add(ls.id);
            if (!unitIds.has(ls.unitId)) errors.push(`curriculum lesson ${ls.id}: unitId "${ls.unitId}" does not resolve`);
            if (!(ls.level in levelIdx)) errors.push(`curriculum lesson ${ls.id}: level "${ls.level}" is not in levels.json`);
            if (!STATUS.includes(ls.status)) errors.push(`curriculum lesson ${ls.id}: status "${ls.status}" must be available | preview | planned`);
            if (!ls.title || !ls.title.trim()) errors.push(`curriculum lesson ${ls.id}: empty title`);
            if (!Array.isArray(ls.skills) || ls.skills.length === 0 || ls.skills.some(s => !skillIds.has(s)))
                errors.push(`curriculum lesson ${ls.id}: skills must be a non-empty list of valid skill ids`);

            if (!Array.isArray(ls.objectives)) errors.push(`curriculum lesson ${ls.id}: objectives must be an array`);
            else for (const oid of ls.objectives) {
                if (!allIds.has(oid)) { errors.push(`curriculum lesson ${ls.id}: objective "${oid}" does not resolve to a learning object`); continue; }
                if (levelIdx[objLevelOf(oid)] > levelIdx[ls.level])
                    errors.push(`curriculum lesson ${ls.id} (${ls.level}): objective ${oid} is a higher level (${objLevelOf(oid)})`);
            }

            const src = ls.source || "";
            if (src === "generate") {
                if (!ls.objectives || ls.objectives.length === 0) errors.push(`curriculum lesson ${ls.id}: source "generate" needs at least one objective`);
            } else if (src.startsWith("steps:")) {
                const key = src.slice(6);
                if (catalogLessonIds && !catalogLessonIds.has(key))
                    errors.push(`curriculum lesson ${ls.id}: source "${src}" — no lesson "${key}" in the index.html catalog`);
            } else if (src.startsWith("view:")) {
                if (!VIEW_TARGETS.has(src.slice(5))) errors.push(`curriculum lesson ${ls.id}: source "${src}" — unknown view`);
            } else {
                errors.push(`curriculum lesson ${ls.id}: source "${src}" must be steps:<id> | view:alphabet | view:vocabulary | generate`);
            }
        }

        /* every non-planned unit that sits at an available level should own ≥1 lesson */
        for (const u of cur.units) {
            const owned = cur.lessons.filter(l => l.unitId === u.id).length;
            if (u.status === "available" && owned === 0) errors.push(`curriculum unit ${u.id}: status "available" but has no lessons`);
        }
    }

    /* -------- M20: lessons authored as data (content/lessons/*.json) -------- */
    if (data.lessons && data.lessons.length) {
        const STEP_TYPES = new Set([
            "explain", "example-set", "practice-choice", "quiz", "trace-letter",
            "reading-practice", "audio-exercise", "listen-repeat", "exercise", "complete",
        ]);
        const FROM_OBJECTIVES_OK = new Set(["example-set", "reading-practice"]);
        const curUnitIds = new Set((data.curriculum ? data.curriculum.units : []).map(u => u.id));
        const catalogIds = data._catalogLessonIds;   // Set or null
        const seenLessonIds = new Set();
        for (const [i, L] of data.lessons.entries()) {
            const where = `lessons[${i}]` + (L && L.id ? ` (${L.id})` : "");
            if (typeof L.id !== "string" || !/^[a-z0-9][a-z0-9-]*$/.test(L.id)) {
                errors.push(`${where}: id must be a kebab-case string`); continue;
            }
            if (seenLessonIds.has(L.id)) errors.push(`lesson ${L.id}: duplicate id among content/lessons/*.json`);
            seenLessonIds.add(L.id);
            if (catalogIds && catalogIds.has(L.id)) errors.push(`lesson ${L.id}: id collides with an inline index.html catalog lesson`);
            if (!L.title || !String(L.title).trim()) errors.push(`lesson ${L.id}: empty title`);
            if (L.unitId != null && !curUnitIds.has(L.unitId)) errors.push(`lesson ${L.id}: unitId "${L.unitId}" does not resolve to a curriculum unit`);
            if (L.curriculumLessonId != null) {
                const cl = data.curriculum && data.curriculum.lessons.find(x => x.id === L.curriculumLessonId);
                if (!cl) errors.push(`lesson ${L.id}: curriculumLessonId "${L.curriculumLessonId}" does not resolve`);
            }
            if (!L.level || !(L.level in levelIdx)) errors.push(`lesson ${L.id}: level "${L.level}" is not in levels.json`);
            if (!Array.isArray(L.skills) || L.skills.length === 0 || L.skills.some(s => !skillIds.has(s)))
                errors.push(`lesson ${L.id}: skills must be a non-empty list of valid skill ids`);
            if (!Array.isArray(L.objectives)) errors.push(`lesson ${L.id}: objectives must be an array`);
            else for (const oid of L.objectives) {
                if (!allIds.has(oid)) { errors.push(`lesson ${L.id}: objective "${oid}" does not resolve to a learning object`); continue; }
                if (L.level in levelIdx && levelIdx[objLevel[oid]] > levelIdx[L.level])
                    errors.push(`lesson ${L.id} (${L.level}): objective ${oid} is a higher level (${objLevel[oid]})`);
            }
            if (!Array.isArray(L.steps) || L.steps.length === 0) errors.push(`lesson ${L.id}: steps must be a non-empty array`);
            else L.steps.forEach((s, j) => {
                if (!s || !STEP_TYPES.has(s.type))
                    errors.push(`lesson ${L.id}: step[${j}] type "${s && s.type}" is not a known renderer`);
                if (s && s.fromObjectives && !FROM_OBJECTIVES_OK.has(s.type))
                    errors.push(`lesson ${L.id}: step[${j}] "fromObjectives" is only valid on ${[...FROM_OBJECTIVES_OK].join(" / ")}`);
                if (s && s.fromObjectives && !(L.objectives || []).some(oid => { const o = data._objById.get(oid); return o && o.kind === "lexeme"; }))
                    errors.push(`lesson ${L.id}: step[${j}] "fromObjectives" but the lesson has no lexeme objectives to expand`);
            });
        }
    }

    /* legacy id map: keys 1..46, values are real lexeme ids, 1:1 */
    if (legacyMap) {
        const keys = Object.keys(legacyMap);
        for (let n = 1; n <= 46; n++) if (!(String(n) in legacyMap)) errors.push(`_legacy-id-map: missing key "${n}"`);
        if (keys.length !== 46) errors.push(`_legacy-id-map: expected 46 keys, found ${keys.length}`);
        const vals = Object.values(legacyMap);
        for (const v of vals) if (!allIds.has(v)) errors.push(`_legacy-id-map: "${v}" is not a real object id`);
        if (new Set(vals).size !== vals.length) errors.push(`_legacy-id-map: values are not 1:1 (a lexeme is claimed by two flashcards)`);
        for (const v of vals) {
            const lx = data.lexemes.find(l => l.id === v);
            if (lx && !(lx.tags || []).includes("legacy-flashcard"))
                errors.push(`_legacy-id-map: ${v} is mapped from a flashcard but is not tagged "legacy-flashcard"`);
        }
    }

    return { errors, data, legacyMap };
}

/* -------------------------------------------------------------------------- */
/* M14.5 + M20.5 — advisory lint (non-blocking, --lint only)                */
/* -------------------------------------------------------------------------- */
// Arabic combining diacritics: the three ḥarakāt (fatḥah/kasrah/ḍammah),
// sukūn, shaddah, tanwīn (three forms), and madd/dagger-alif. Presence of
// any one of these is what "carries ḥarakāt" means for coverage purposes —
// this checks *presence*, never correctness, per build-content.js's own
// stated scope (structural/coverage only, not linguistic).
const HARAKAT_RE = /[ً-ْٰ]/;

function lint(data, legacyMap) {
    const warnings = [];

    /* ḥarakāt coverage — fields expected to carry vowel marks */
    const checkHarakat = (label, text) => {
        if (typeof text === "string" && text && !HARAKAT_RE.test(text)) warnings.push(`ḥarakāt coverage: ${label} has no vowel marks — "${text}"`);
    };
    for (const l of data.lexemes) {
        checkHarakat(`lexeme ${l.id} (ar)`, l.ar);
        if (l.example) checkHarakat(`lexeme ${l.id} (example.ar)`, l.example.ar);
    }
    for (const lt of data.letters) checkHarakat(`letter ${lt.id} (name)`, lt.name);
    for (const s of data.syllables) checkHarakat(`syllable ${s.id} (ar)`, s.ar);
    for (const t of data.texts) {
        checkHarakat(`text ${t.id} (vowelled)`, t.vowelled);
        for (const [i, w] of (t.words || []).entries()) checkHarakat(`text ${t.id} (words[${i}].surface)`, w.surface);
    }

    /* orphaned objects — never referenced by a prereq edge, a syllable's
       exampleWord, a grammar example, a curriculum lesson objective, or the
       legacy id map. Advisory: plenty of content is legitimately authored
       ahead of the curriculum slot that will eventually reference it. */
    const referenced = new Set();
    for (const key of Object.keys(FILES)) for (const o of data[key]) for (const p of (o.prereqs || [])) referenced.add(p);
    for (const s of data.syllables) if (s.exampleWord) referenced.add(s.exampleWord);
    for (const g of data.grammar) for (const ref of (g.examples || [])) referenced.add(ref);
    if (data.curriculum) for (const ls of data.curriculum.lessons) for (const oid of (ls.objectives || [])) referenced.add(oid);
    if (legacyMap) for (const v of Object.values(legacyMap)) referenced.add(v);

    const ORPHAN_KINDS = ["lexemes", "texts", "grammar"]; // reference/foundational content (letters, marks, syllables) is expected to stand alone
    for (const key of ORPHAN_KINDS) for (const o of data[key]) {
        if (!referenced.has(o.id)) warnings.push(`orphaned: ${o.id} (${key}) is not referenced by any prereq, syllable, grammar example, curriculum objective, or legacy map`);
    }

    /* M20.5 — texts.json's hand-authored reduced/unvowelled drift check.
       Mirrors index.html's deriveReducedForm()/deriveUnvowelledForm()
       exactly (same two regexes) so this can never disagree with what the
       app itself would compute. A mismatch is a flag for human review, not
       an auto-fix — some "reduced" choices are stylistic (see the M20.5
       scope doc); an empty reduced/unvowelled field is unauthored, not
       wrong, and isn't flagged. */
    const deriveReducedForm = (v) => String(v || "").replace(/[ً-ّٰۖ-ۭ]/g, "");
    const deriveUnvowelledForm = (v) => String(v || "").replace(/[ً-ْٰۖ-ۭ]/g, "");
    for (const t of data.texts) {
        if (!t.vowelled) continue;
        if (t.reduced && deriveReducedForm(t.vowelled) !== t.reduced)
            warnings.push(`text ${t.id}: reduced "${t.reduced}" does not match the mechanical derivation "${deriveReducedForm(t.vowelled)}" from vowelled`);
        if (t.unvowelled && deriveUnvowelledForm(t.vowelled) !== t.unvowelled)
            warnings.push(`text ${t.id}: unvowelled "${t.unvowelled}" does not match the mechanical derivation "${deriveUnvowelledForm(t.vowelled)}" from vowelled`);
    }

    return warnings;
}

function findCycle(graph) {
    const WHITE = 0, GREY = 1, BLACK = 2;
    const color = new Map([...graph.keys()].map(k => [k, WHITE]));
    const stack = [];
    let cycle = null;
    function dfs(u) {
        color.set(u, GREY); stack.push(u);
        for (const v of graph.get(u) || []) {
            if (!graph.has(v)) continue;
            if (color.get(v) === GREY) { cycle = stack.slice(stack.indexOf(v)).concat(v); return true; }
            if (color.get(v) === WHITE && dfs(v)) return true;
        }
        color.set(u, BLACK); stack.pop(); return false;
    }
    for (const k of graph.keys()) if (color.get(k) === WHITE && dfs(k)) break;
    return cycle;
}

/* -------------------------------------------------------------------------- */
/* Compile                                                                   */
/* -------------------------------------------------------------------------- */
function compile(data, legacyMap) {
    // Source-file order is preserved verbatim — it is semantically meaningful
    // (letters run alif→yāʾ, harakāt fatḥah→ḍammah, reading passages in lesson
    // order, …). Deterministic because the JSON files are the source of truth.
    const section = (key) => {
        const rows = data[key].map(o => "  " + JSON.stringify(o) + ",");
        return `"${key}": [\n${rows.join("\n")}\n]`;
    };
    // curriculum is an object { levels, units, lessons }; emit each as a row list.
    const curriculumBlock = () => {
        const arr = (name) => {
            const rows = (data.curriculum[name] || []).map(o => "    " + JSON.stringify(o) + ",");
            return `  "${name}": [\n${rows.join("\n")}\n  ]`;
        };
        return `"curriculum": {\n${[arr("levels"), arr("units"), arr("lessons")].join(",\n")}\n}`;
    };
    const mapRows = Object.keys(legacyMap)
        .sort((a, b) => Number(a) - Number(b))
        .map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(legacyMap[k])},`);

    // M20 — lessons authored as data. `fromObjectives` steps are expanded here
    // from the referenced objects, so no Arabic is inlined in the lesson file.
    const compiledLessons = (data.lessons || []).map(L => {
        const obj = id => data._objById && data._objById.get(id);
        const steps = (L.steps || []).map(s => {
            if ((s.type === "example-set" || s.type === "reading-practice") && s.fromObjectives) {
                const lex = (L.objectives || []).map(obj).filter(o => o && o.kind === "lexeme");
                const out = Object.assign({}, s); delete out.fromObjectives;
                if (s.type === "example-set") out.items = lex.map(l => ({ symbolWord: l.ar, name: l.en, translit: l.translit, sound: l.pos || "", examples: [] }));
                else out.items = lex.map(l => ({ arabic: l.ar, translit: l.translit, english: l.en }));
                return out;
            }
            return s;
        });
        return { id: L.id, title: L.title, curriculumLessonId: L.curriculumLessonId || null, objectives: L.objectives || [], steps };
    });

    return [
        MARKER_START,
        "/* Learning-object content, compiled from content/*.json by",
        "   tools/build-content.js. Do not hand-edit. Regenerate:",
        "     node tools/build-content.js --write-app */",
        "const CONTENT = {",
        section("skills") + ",",
        section("levels") + ",",
        section("descriptors") + ",",
        section("lexemes") + ",",
        section("letters") + ",",
        section("marks") + ",",
        section("syllables") + ",",
        section("grammar") + ",",
        section("texts") + ",",
        curriculumBlock() + ",",
        `"lessons": [\n${compiledLessons.map(o => "  " + JSON.stringify(o) + ",").join("\n")}\n]` + ",",
        `"legacyFlashcardId": {\n${mapRows.join("\n")}\n}`,
        "};",
        MARKER_END,
    ].join("\n");
}

function extractBlock(html) {
    const i = html.indexOf(MARKER_START);
    const j = html.indexOf(MARKER_END);
    if (i === -1 || j === -1) return null;
    return html.slice(i, j + MARKER_END.length);
}

/* -------------------------------------------------------------------------- */
/* Main                                                                      */
/* -------------------------------------------------------------------------- */
// M20's linguistic linter is a separate pure module; alias it so it doesn't
// collide with this file's own advisory `lint()` (M14.5 + M20.5).
const { lint: linguisticLint } = require("./content-lint.js");

function main() {
    const args = new Set(process.argv.slice(2));
    const { errors, data, legacyMap } = load();

    if (errors.length) {
        console.error("content validation FAILED:");
        errors.forEach(e => console.error("  - " + e));
        process.exit(1);
    }

    /* M20 — linguistic lint. HARD errors block every run (a colloquialism in
       MSA content, an Arabic-Indic digit outside the numbers topic, a
       translit/script emphatic mismatch are never acceptable). Its WARNINGS
       are advisory and only surface under --lint, alongside M14.5/M20.5. */
    const ling = linguisticLint(data, data._wordlists, data._lintAllow);
    if (ling.errors.length) {
        console.error("linguistic lint FAILED:");
        ling.errors.forEach(e => console.error("  - " + e));
        process.exit(1);
    }

    if (args.has("--lint")) {
        const warnings = [
            ...ling.warnings.map(w => "linguistic — " + w),
            ...lint(data, legacyMap),
        ];
        if (warnings.length) {
            console.log(`content lint — ${warnings.length} advisory warning(s):`);
            warnings.forEach(w => console.log("  ! " + w));
        } else {
            console.log("content lint — clean, no advisory warnings.");
        }
        return;
    }

    const counts = Object.fromEntries(Object.keys(FILES).map(k => [k, data[k].length]));
    const block = compile(data, legacyMap);
    const html = fs.readFileSync(INDEX_HTML, "utf8");
    const current = extractBlock(html);

    if (args.has("--check")) {
        if (current === null) { console.error("--check: CONTENT markers not found in index.html"); process.exit(1); }
        if (lf(current) !== lf(block)) {
            console.error("STALE — index.html CONTENT block is out of date. Run: node tools/build-content.js --write-app");
            process.exit(1);
        }
        console.log(`content OK and index.html in sync — ${sum(counts)} objects (${describe(counts)}).`);
        return;
    }

    if (args.has("--write-app")) {
        if (current === null) {
            console.error("\n--write-app: CONTENT markers not found in index.html. Add this once, in the DATA section:\n");
            console.error(MARKER_START + "\nconst CONTENT = {};\n" + MARKER_END + "\n");
            process.exit(2);
        }
        const eol = html.includes("\r\n") ? "\r\n" : "\n";
        const updated = html.replace(current, block.replace(/\n/g, eol));
        if (lf(updated) === lf(html)) console.log("index.html CONTENT block already current.");
        else { fs.writeFileSync(INDEX_HTML, updated); console.log("updated index.html CONTENT block."); }
    }

    console.log("");
    console.log("content validated — " + sum(counts) + " learning objects");
    for (const [k, n] of Object.entries(counts)) console.log("  " + k.padEnd(12) + n);
    console.log("  legacy id map  " + Object.keys(legacyMap).length);
    console.log("  taxonomy       " + (data.skills || []).length + " skills, " + (data.levels || []).length + " levels, " + (data.descriptors || []).length + " descriptors");
    if (data.curriculum) console.log("  curriculum     " + data.curriculum.units.length + " units, " + data.curriculum.lessons.length + " lessons");
    console.log("  lessons (data) " + (data.lessons || []).length);
    if (!args.has("--write-app")) console.log("\n(run with --write-app to splice into index.html, or --check to verify)");
}

function sum(c) { return Object.values(c).reduce((a, b) => a + b, 0); }
function describe(c) { return Object.entries(c).map(([k, n]) => `${n} ${k}`).join(", "); }

main();
